<?php
//    define ('FM_IMG_EXTENSION', '.png');
    define ('FM_IMG_EXTENSION', '.gif');
    
    define ('FM_IMG_BACK',     'back'.FM_IMG_EXTENSION);
    define ('FM_IMG_BLOCKDEV', 'blockdev'.FM_IMG_EXTENSION);
    define ('FM_IMG_BROKEN',   'broken'.FM_IMG_EXTENSION);
    define ('FM_IMG_CHARDEV',  'chardev'.FM_IMG_EXTENSION);
    define ('FM_IMG_DIR',      'dir'.FM_IMG_EXTENSION);
    define ('FM_IMG_DOWNLOAD', 'download'.FM_IMG_EXTENSION);
    define ('FM_IMG_EDIT',     'edit'.FM_IMG_EXTENSION);
    define ('FM_IMG_FIFO',     'fifo'.FM_IMG_EXTENSION);
    define ('FM_IMG_REFRESH',  'refresh'.FM_IMG_EXTENSION);
    define ('FM_IMG_RENAME',   'rename'.FM_IMG_EXTENSION);
    define ('FM_IMG_SOCKET',   'socket'.FM_IMG_EXTENSION);
    define ('FM_IMG_SYMLINK',  'symlink'.FM_IMG_EXTENSION);
    define ('FM_IMG_TEXT',     'text'.FM_IMG_EXTENSION);
    
?>